[project]
name = "aiml4os-wp11-reconstruction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ibis-framework[duckdb]>=12.0.0",
    "lightgbm>=4.6.0",
    "scikit-learn>=1.6.1"
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.5.9",
    "matplotlib>=3.11.0",
    "networkx>=3.6.1",
    "seaborn>=0.13.2",
    "snakemake>=9.23.1",
]
